import * as React from 'react';
import Header from '../Components/Header';
import '../Styles/Product-List.css';
import { useEffect, useState } from 'react';
import ProductCardAll from '../Components/AllProductCard';

interface Product {
    name: string;
    category: string;
    imageUrl: string;
    originalPrice: number;
    discountedPrice?: number;
    salesQuantity: number;
}

interface Category {
    name: string;
    products: Product[];
}

const categories: Category[] = [
    {
        name: 'Thời trang nam',
        products: [
            {
                name: 'ÁO DÀI TAY SEEVENSTU // LONGSLEEVE DETAIL FORM BOXYYYYYYYYYYYYYYY',
                category: 'Áo',
                imageUrl:
                    'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 300000,
                // discountedPrice: 400000,
                salesQuantity: 100,
            },
            {
                name: 'Quần tây',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 500000,
                salesQuantity: 80,
            },
            {
                name: 'Áo sơ mi',
                category: 'Áo',
                imageUrl:
                    'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 100,
            },
            {
                name: 'Quần tây',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 500000,
                salesQuantity: 80,
            },
            {
                name: 'Áo sơ mi',
                category: 'Áo',
                imageUrl:
                    'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 100,
            },
            {
                name: 'Quần tây',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 500000,
                salesQuantity: 80,
            },
            {
                name: 'Áo sơ mi',
                category: 'Áo',
                imageUrl:
                    'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 100,
            },
            {
                name: 'Quần tây',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 500000,
                salesQuantity: 80,
            },
        ],
    },
    {
        name: 'Áo khoác',
        products: [
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
            {
                name: 'Áo khoác da',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1500000,
                discountedPrice: 1200000,
                salesQuantity: 60,
            },
            {
                name: 'Áo khoác gió',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 800000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
        ],
    },
    {
        name: 'Áo vest và blazer',
        products: [
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
            {
                name: 'Vest đen',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 70,
            },
            {
                name: 'Blazer xanh',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 1400000,
                discountedPrice: 1100000,
                salesQuantity: 85,
            },
        ],
    },
    {
        name: 'Áo hoodie',
        products: [
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
            {
                name: 'Hoodie đỏ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 700000,
                discountedPrice: 550000,
                salesQuantity: 120,
            },
            {
                name: 'Hoodie xám',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 95,
            },
        ],
    },
    {
        name: 'Áo len áo nỉ',
        products: [
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
            {
                name: 'Áo len cổ lọ',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tn',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 110,
            },
            {
                name: 'Áo nỉ dáng dài',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 650000,
                discountedPrice: 520000,
                salesQuantity: 85,
            },
        ],
    },
    {
        name: 'Quần jeans',
        products: [
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
            {
                name: 'Jeans xanh',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 130,
            },
            {
                name: 'Jeans đen',
                category: 'Quần jeans',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 100,
            },
        ],
    },
    {
        name: 'Quần dài/quần âu',
        products: [
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
            {
                name: 'Quần âu xám',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 800000,
                discountedPrice: 640000,
                salesQuantity: 90,
            },
            {
                name: 'Quần dài màu be',
                category: 'Quần dài/quần âu',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 850000,
                discountedPrice: 680000,
                salesQuantity: 75,
            },
        ],
    },
    {
        name: 'Quần short',
        products: [
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
            {
                name: 'Short kaki',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 400000,
                discountedPrice: 320000,
                salesQuantity: 140,
            },
            {
                name: 'Short jean',
                category: 'Quần short',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 450000,
                discountedPrice: 360000,
                salesQuantity: 110,
            },
        ],
    },
    {
        name: 'Áo',
        products: [
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
            {
                name: 'Áo sơ mi trắng',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 500000,
                discountedPrice: 400000,
                salesQuantity: 95,
            },
            {
                name: 'Áo thun',
                category: 'Áo',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 300000,
                discountedPrice: 240000,
                salesQuantity: 150,
            },
        ],
    },
    {
        name: 'Áo ba lỗ',
        products: [
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
            {
                name: 'Áo ba lỗ thể thao',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 100,
            },
            {
                name: 'Áo ba lỗ cotton',
                category: 'Áo ba lỗ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 280000,
                discountedPrice: 220000,
                salesQuantity: 90,
            },
        ],
    },
    {
        name: 'Đồ lót',
        products: [
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
            {
                name: 'Quần lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 150000,
                discountedPrice: 120000,
                salesQuantity: 200,
            },
            {
                name: 'Áo lót',
                category: 'Đồ lót',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 180000,
                discountedPrice: 140000,
                salesQuantity: 180,
            },
        ],
    },
    {
        name: 'Đồ ngủ',
        products: [
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr2vxztg6x09a7_tng',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
            {
                name: 'Pijama',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image23.jpg',
                originalPrice: 600000,
                discountedPrice: 480000,
                salesQuantity: 80,
            },
            {
                name: 'Đồ ngủ ngắn',
                category: 'Đồ ngủ',
                imageUrl: 'path/to/image24.jpg',
                originalPrice: 550000,
                discountedPrice: 440000,
                salesQuantity: 75,
            },
        ],
    },
    {
        name: 'Đồ bộ',
        products: [
            {
                name: 'Đồ bộ vải coton',
                category: 'Đồ bộ',
                imageUrl: 'path/to/image25.jpg',
                originalPrice: 700000,
                discountedPrice: 560000,
                salesQuantity: 85,
            },
            {
                name: 'Đồ bộ ngủ',
                category: 'Đồ bộ',
                imageUrl: 'path/to/image26.jpg',
                originalPrice: 750000,
                discountedPrice: 600000,
                salesQuantity: 90,
            },
        ],
    },
    {
        name: 'Vớ/tất',
        products: [
            {
                name: 'Tất ngắn',
                category: 'Vớ/tất',
                imageUrl: 'path/to/image27.jpg',
                originalPrice: 100000,
                discountedPrice: 80000,
                salesQuantity: 300,
            },
            {
                name: 'Tất dài',
                category: 'Vớ/tất',
                imageUrl: 'path/to/image28.jpg',
                originalPrice: 120000,
                discountedPrice: 100000,
                salesQuantity: 250,
            },
        ],
    },
    {
        name: 'Trang phục truyền thống',
        products: [
            {
                name: 'Áo dài',
                category: 'Trang phục truyền thống',
                imageUrl: 'path/to/image29.jpg',
                originalPrice: 2000000,
                discountedPrice: 1800000,
                salesQuantity: 40,
            },
            {
                name: 'Sườn xám',
                category: 'Trang phục truyền thống',
                imageUrl: 'path/to/image30.jpg',
                originalPrice: 2200000,
                discountedPrice: 2000000,
                salesQuantity: 35,
            },
        ],
    },
    {
        name: 'Đồ hóa trang',
        products: [
            {
                name: 'Trang phục siêu anh hùng',
                category: 'Đồ hóa trang',
                imageUrl: 'path/to/image31.jpg',
                originalPrice: 500000,
                discountedPrice: 450000,
                salesQuantity: 60,
            },
            {
                name: 'Trang phục cổ tích',
                category: 'Đồ hóa trang',
                imageUrl: 'path/to/image32.jpg',
                originalPrice: 550000,
                discountedPrice: 500000,
                salesQuantity: 55,
            },
        ],
    },
    {
        name: 'Trang phục ngành nghề',
        products: [
            {
                name: 'Đồng phục bác sĩ',
                category: 'Trang phục ngành nghề',
                imageUrl: 'path/to/image33.jpg',
                originalPrice: 700000,
                discountedPrice: 650000,
                salesQuantity: 45,
            },
            {
                name: 'Đồng phục lính cứu hỏa',
                category: 'Trang phục ngành nghề',
                imageUrl: 'path/to/image34.jpg',
                originalPrice: 800000,
                discountedPrice: 750000,
                salesQuantity: 50,
            },
        ],
    },
    {
        name: 'Khác',
        products: [
            {
                name: 'Đồ bơi',
                category: 'Khác',
                imageUrl: 'path/to/image35.jpg',
                originalPrice: 400000,
                discountedPrice: 350000,
                salesQuantity: 70,
            },
            {
                name: 'Đồ tập gym',
                category: 'Khác',
                imageUrl: 'path/to/image36.jpg',
                originalPrice: 450000,
                discountedPrice: 400000,
                salesQuantity: 65,
            },
        ],
    },
    {
        name: 'Trang sức nam',
        products: [
            {
                name: 'Nhẫn',
                category: 'Trang sức nam',
                imageUrl: 'path/to/image37.jpg',
                originalPrice: 1000000,
                discountedPrice: 900000,
                salesQuantity: 55,
            },
            {
                name: 'Dây chuyền',
                category: 'Trang sức nam',
                imageUrl: 'path/to/image38.jpg',
                originalPrice: 1200000,
                discountedPrice: 1000000,
                salesQuantity: 60,
            },
        ],
    },
    {
        name: 'Kính mắt nam',
        products: [
            {
                name: 'Kính mát',
                category: 'Kính mắt nam',
                imageUrl: 'path/to/image39.jpg',
                originalPrice: 300000,
                discountedPrice: 250000,
                salesQuantity: 90,
            },
            {
                name: 'Kính cận',
                category: 'Kính mắt nam',
                imageUrl: 'path/to/image40.jpg',
                originalPrice: 350000,
                discountedPrice: 300000,
                salesQuantity: 75,
            },
        ],
    },
    {
        name: 'Thắt lưng nam',
        products: [
            {
                name: 'Thắt lưng da',
                category: 'Thắt lưng nam',
                imageUrl: 'path/to/image41.jpg',
                originalPrice: 500000,
                discountedPrice: 450000,
                salesQuantity: 85,
            },
            {
                name: 'Thắt lưng vải',
                category: 'Thắt lưng nam',
                imageUrl: 'path/to/image42.jpg',
                originalPrice: 400000,
                discountedPrice: 350000,
                salesQuantity: 90,
            },
        ],
    },
    {
        name: 'Cà vạt',
        products: [
            {
                name: 'Cà vạt sọc',
                category: 'Cà vạt',
                imageUrl: 'path/to/image43.jpg',
                originalPrice: 200000,
                discountedPrice: 180000,
                salesQuantity: 70,
            },
            {
                name: 'Cà vạt trơn',
                category: 'Cà vạt',
                imageUrl: 'path/to/image44.jpg',
                originalPrice: 220000,
                discountedPrice: 200000,
                salesQuantity: 65,
            },
        ],
    },
    {
        name: 'Phụ kiện nam',
        products: [
            {
                name: 'Mũ',
                category: 'Phụ kiện nam',
                imageUrl: 'path/to/image45.jpg',
                originalPrice: 250000,
                discountedPrice: 200000,
                salesQuantity: 80,
            },
            {
                name: 'Găng tay',
                category: 'Phụ kiện nam',
                imageUrl: 'path/to/image46.jpg',
                originalPrice: 180000,
                discountedPrice: 150000,
                salesQuantity: 85,
            },
        ],
    },
];

const PRODUCTS_PER_PAGE = 60;

export default function ProductListItem() {
    const [showAll, setShowAll] = useState(false);
    const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
    const [selectedSubCategories, setSelectedSubCategories] = useState<Set<string>>(new Set());
    const [currentPage, setCurrentPage] = useState(1);

    const itemsToShow = showAll ? categories : categories.slice(0, 5);
    const allProducts =
        selectedCategory === 'Tất Cả Danh Mục'
            ? categories.flatMap((category) => category.products)
            : categories.find((category) => category.name === selectedCategory)?.products || [];

    const filteredProducts = allProducts.filter(
        (product) => selectedSubCategories.size === 0 || selectedSubCategories.has(product.category),
    );

    const totalPages = Math.ceil(filteredProducts.length / PRODUCTS_PER_PAGE);
    const startIndex = (currentPage - 1) * PRODUCTS_PER_PAGE;
    const endIndex = startIndex + PRODUCTS_PER_PAGE;
    const productsToDisplay = filteredProducts.slice(startIndex, endIndex);

    useEffect(() => {
        setSelectedCategory('Tất Cả Danh Mục');
    }, []);

    const handleCategoryClick = (categoryName: string) => {
        setSelectedCategory(categoryName);
        setCurrentPage(1); // Reset to the first page when category changes
    };

    const handleSubCategoryChange = (subCategory: string) => {
        setSelectedSubCategories((prev) => {
            const newSet = new Set(prev);
            if (newSet.has(subCategory)) {
                newSet.delete(subCategory);
            } else {
                newSet.add(subCategory);
            }
            return newSet;
        });
        setCurrentPage(1); // Reset to the first page when filters change
    };

    const handlePageChange = (newPage: number) => {
        setCurrentPage(newPage);
    };

    return (
        <>
            <Header />
            <div className="Product-List-Container">
                <div className="row">
                    <div className="col-2 Left-Product-List-Container">
                        <div className="pt-3 Tl1-LPLC">
                            <button
                                onClick={() => handleCategoryClick('Tất Cả Danh Mục')}
                                className={selectedCategory === 'Tất Cả Danh Mục' ? 'selected' : ''}
                            >
                                Tất Cả Danh Mục
                            </button>
                        </div>
                        <div className="Tl1-Container-LPLC">
                            {itemsToShow.map((category, index) => (
                                <div key={index} className="py-2">
                                    <h2>
                                        <button
                                            onClick={() => handleCategoryClick(category.name)}
                                            className={category.name === selectedCategory ? 'selected' : ''}
                                        >
                                            {category.name}
                                        </button>
                                    </h2>
                                </div>
                            ))}
                            <div className="pt-1 button-Tl1">
                                {!showAll && categories.length > 5 && (
                                    <button onClick={() => setShowAll(true)} className="show-more-button">
                                        Xem thêm
                                    </button>
                                )}
                                {showAll && (
                                    <button onClick={() => setShowAll(false)} className="show-less-button">
                                        Thu gọn
                                    </button>
                                )}
                            </div>
                        </div>
                        <div className="pt-5 Tl2-Container-LPLC">
                            <h2>Bộ Lọc Sản Phẩm</h2>
                            <div className="checkbox-container">
                                {Array.from(
                                    new Set(
                                        categories.flatMap((category) =>
                                            category.products.map((product) => product.category),
                                        ),
                                    ),
                                ).map((subCategory, index) => (
                                    <div key={index} className="py-2 checkbox-item">
                                        <label>
                                            <input
                                                type="checkbox"
                                                checked={selectedSubCategories.has(subCategory)}
                                                onChange={() => handleSubCategoryChange(subCategory)}
                                            />
                                            {subCategory}
                                        </label>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                    <div className="col-10 Right-Product-List-Container">
                        {productsToDisplay.length > 0 && (
                            <div className="product-list-RPLC">
                                {productsToDisplay.map((product, index) => (
                                    <ProductCardAll
                                        key={index}
                                        name={product.name}
                                        imageUrl={product.imageUrl}
                                        originalPrice={product.originalPrice}
                                        discountedPrice={product.discountedPrice}
                                        salesQuantity={product.salesQuantity}
                                    />
                                ))}
                            </div>
                        )}
                        <div className="pagination-controls">
                            <button onClick={() => handlePageChange(currentPage - 1)} disabled={currentPage === 1}>
                                Previous
                            </button>
                            <span>
                                Page {currentPage} of {totalPages}
                            </span>
                            <button
                                onClick={() => handlePageChange(currentPage + 1)}
                                disabled={currentPage === totalPages}
                            >
                                Next
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
